name: surveymonkey-development
static_sites:
- build_command: npx nx serve surveychimp-survey-spa
  catchall_document: index.html
  environment_slug: node-js
  github:
    branch: development
    deploy_on_push: true
    repo: markusJsU21/surveychimp
  name: frontend-spa-dev
  routes:
  - path: /
  source_dir: /