databases:
- cluster_name: mongo-db
  engine: MONGODB
  name: mongo-db
  production: true
  version: "5"
  db_name: "prod"
name: surveymonkey-production
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${mongo-db.DATABASE_URL}
  - key: CA_CERT
    scope: RUN_TIME
    value: ${mongo-db.CA_CERT}
  github:
    branch: main
    repo: markusJsU21/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp
  routes:
  - path: /
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /