@baseUrl=http://localhost:3333

POST {{baseUrl}}/survey
Content-Type: application/json

{
    "recipient": {
        "name": "Meeko",
        "mobileNumber": "070 123 12 12"
    }
}

###

GET {{baseUrl}}/survey/63637bc0b6614232d5158620

###

PATCH {{baseUrl}}/survey/63637bc0b6614232d5158620
Content-Type: application/json

{
    "rating": 3,
    "comment": "Det var toppen!"
}