@baseUrl=http://localhost:3333

POST {{baseUrl}}/survey
Content-Type: application/json

{
    "recipient": {
        "name": "Meeko",
        "mobileNumber": "070 123 12 12"
    }
}

###

GET {{baseUrl}}/survey/635bd74adf7ebe382b6861ba

###

PATCH {{baseUrl}}/survey/635a3b76447595cdc91bcfdd
Content-Type: application/json

{
    "rating": 3,
    "comment": "Det var toppen!"
}