@baseUrl=http://localhost:3333

POST {{baseUrl}}/survey
Content-Type: application/json

{
    "recipient": {
        "name": "Testperson",
        "mobileNumber": "070 111 99 99"
    }
}

###

GET {{baseUrl}}/survey/636b70bae60f35cca48bdcc5

###
GET {{baseUrl}}/survey

###

PATCH {{baseUrl}}/survey/63637bc0b6614232d5158620
Content-Type: application/json

{
    "rating": 3,
    "comment": "Det var toppen!"
}

###
GET {{baseUrl}}/healthcheck

