<<<<<<< HEAD:.github/workflows/build-and-test-syrvey.yaml
name: Node.js CI
on:
 
  pull_request:
    branches: [ development]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
=======
name: Node.js CI
on:

  pull_request:
    branches: [ development]
    paths: 'apps/surveychimp-survey-spa**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
>>>>>>> 18216b2b00813a27ad414fe9d3e029481a696aa2:.github/workflows/build-and-test-spa.yaml
      - run: npm run test:survey-spa